# Select base Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy necessary files into the container
COPY . /app

# Install required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose ports if needed (used by the subscriber)
EXPOSE 5560

# Command that runs when the container starts
CMD ["python", "/app/sub.py"]
