# Use a base Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all necessary files into the container
COPY . /app

# Install required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port (if needed for communication)
EXPOSE 5559

# Command to run when the container starts
CMD ["python", "/app/pub.py"]
